# Generated by Django 3.1.7 on 2021-04-15 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('father_name', models.CharField(max_length=50, verbose_name='Father Name')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(max_length=50, verbose_name='Gender')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('pin', models.PositiveIntegerField(verbose_name='City Post code')),
                ('mobile', models.PositiveIntegerField(verbose_name='Mobile Number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Adress')),
                ('job_city', models.CharField(max_length=50, verbose_name='JOb city')),
                ('state', models.CharField(choices=[('Balochistan', 'Balochistan'), ('Khyber Pakhtunkhwa', 'Khyber Pakhtunkhwa'), ('Punjab', 'Punjab'), ('Sindh', 'Sindh')], max_length=50, verbose_name='Select State')),
                ('image', models.ImageField(upload_to='images', verbose_name='Uploade Image')),
                ('file', models.FileField(upload_to='document', verbose_name='Resume PDF')),
            ],
        ),
    ]
